<div class="h-index-icons">
<?php
    $this->headTitle(
        $this->translate(
            'headTitle'
        )
    )
?>

<div class="l-bottom-after-icons clearfix">
    <div class="b-vacancies-amount">
        <?php echo $this->translate('vacanciesOnline', $this->vacancies_online, $this->date) ?>
    </div>
    <div class="b-customer-login">
        <a href="/login"><?php echo $this->translate("login")?></a>
    </div>
</div>
</div>